version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: daily
    labels:
      - dependencies
      - skip-changelog
      - python
